### ISSUE TITLE
Switch From if-else to match

### ISSUE THREAD

**Issue by ShearStress021** [thelegendev/Cipherion#11]
**For readablily making use of match case instead of if-else, makes the code readable**
![Screenshot from 2024-11-01 06-15-11](https://github.com/user-attachments/assets/c693187b-c8aa-4e21-8aa7-b5cc1062228b)

**Comment by diptodeepb** [comment]
Hi @ShearStress021 ,

I believe that switching from `if-else` to `match-case` is not necessary here for such a simplistic approach, since `match-case` is generally used in scenarios where pattern matching, handling of multiple conditions or data structures is involved, or even for handling complex structures.
