### ISSUE TITLE
[Enhancement] Adding a window-based GUI using tkinter

### ISSUE THREAD

**Issue by ashoka0402** [thelegendev/Cipherion#5]
After the authentication is granted, encryption/decryption window pops up

![hack](https://github.com/user-attachments/assets/3a375a70-b3eb-4c64-a1f4-7409f2da6572)

**Comment by diptodeepb** [comment]
Hi @ashoka0402 ,
While I highly appreciate your interest in contributing to Cipherion, I’ve decided to stick with the CLI for now. It just keeps things more secure and feels more authentic for our most of our end users who seem to be of a technical background. By using tkinter, there's not much UX being improved since it's just a replication of the CLI's functionality, and no additional features support the UX, apart from the very basic UI. 

In overall, the CLI is just faster, and since everyone still needs to run the program for the GUI to start, it wouldn’t really add much value to the project. I hope you understand, and I’d love to hear any ideas you have for the CLI. Thanks!
